// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type beacondetectBeaconKey struct {
	_     structs.HostLayout
	Pid   uint32
	Daddr uint32
	Dport uint16
	Pad   uint16
}

type beacondetectBeaconVal struct {
	_             structs.HostLayout
	LastNs        uint64
	IntervalSumNs uint64
	IntervalCount uint64
	MinIntervalNs uint64
	MaxIntervalNs uint64
	SendCount     uint64
}

// loadBeacondetect returns the embedded CollectionSpec for beacondetect.
func loadBeacondetect() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BeacondetectBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load beacondetect: %w", err)
	}

	return spec, err
}

// loadBeacondetectObjects loads beacondetect and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*beacondetectObjects
//	*beacondetectPrograms
//	*beacondetectMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBeacondetectObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBeacondetect()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// beacondetectSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type beacondetectSpecs struct {
	beacondetectProgramSpecs
	beacondetectMapSpecs
	beacondetectVariableSpecs
}

// beacondetectProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type beacondetectProgramSpecs struct {
	HandleBeaconSendmsg *ebpf.ProgramSpec `ebpf:"handle_beacon_sendmsg"`
}

// beacondetectMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type beacondetectMapSpecs struct {
	BeaconAccum *ebpf.MapSpec `ebpf:"beacon_accum"`
}

// beacondetectVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type beacondetectVariableSpecs struct {
}

// beacondetectObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBeacondetectObjects or ebpf.CollectionSpec.LoadAndAssign.
type beacondetectObjects struct {
	beacondetectPrograms
	beacondetectMaps
	beacondetectVariables
}

func (o *beacondetectObjects) Close() error {
	return _BeacondetectClose(
		&o.beacondetectPrograms,
		&o.beacondetectMaps,
	)
}

// beacondetectMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBeacondetectObjects or ebpf.CollectionSpec.LoadAndAssign.
type beacondetectMaps struct {
	BeaconAccum *ebpf.Map `ebpf:"beacon_accum"`
}

func (m *beacondetectMaps) Close() error {
	return _BeacondetectClose(
		m.BeaconAccum,
	)
}

// beacondetectVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadBeacondetectObjects or ebpf.CollectionSpec.LoadAndAssign.
type beacondetectVariables struct {
}

// beacondetectPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBeacondetectObjects or ebpf.CollectionSpec.LoadAndAssign.
type beacondetectPrograms struct {
	HandleBeaconSendmsg *ebpf.Program `ebpf:"handle_beacon_sendmsg"`
}

func (p *beacondetectPrograms) Close() error {
	return _BeacondetectClose(
		p.HandleBeaconSendmsg,
	)
}

func _BeacondetectClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed beacondetect_x86_bpfel.o
var _BeacondetectBytes []byte
