// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type cgthrottleThrottleVal struct {
	_     structs.HostLayout
	Count uint64
}

// loadCgthrottle returns the embedded CollectionSpec for cgthrottle.
func loadCgthrottle() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_CgthrottleBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load cgthrottle: %w", err)
	}

	return spec, err
}

// loadCgthrottleObjects loads cgthrottle and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*cgthrottleObjects
//	*cgthrottlePrograms
//	*cgthrottleMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadCgthrottleObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadCgthrottle()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// cgthrottleSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type cgthrottleSpecs struct {
	cgthrottleProgramSpecs
	cgthrottleMapSpecs
	cgthrottleVariableSpecs
}

// cgthrottleProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type cgthrottleProgramSpecs struct {
	HandleThrottleCfsRq *ebpf.ProgramSpec `ebpf:"handle_throttle_cfs_rq"`
}

// cgthrottleMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type cgthrottleMapSpecs struct {
	ThrottleAccum *ebpf.MapSpec `ebpf:"throttle_accum"`
}

// cgthrottleVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type cgthrottleVariableSpecs struct {
}

// cgthrottleObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadCgthrottleObjects or ebpf.CollectionSpec.LoadAndAssign.
type cgthrottleObjects struct {
	cgthrottlePrograms
	cgthrottleMaps
	cgthrottleVariables
}

func (o *cgthrottleObjects) Close() error {
	return _CgthrottleClose(
		&o.cgthrottlePrograms,
		&o.cgthrottleMaps,
	)
}

// cgthrottleMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadCgthrottleObjects or ebpf.CollectionSpec.LoadAndAssign.
type cgthrottleMaps struct {
	ThrottleAccum *ebpf.Map `ebpf:"throttle_accum"`
}

func (m *cgthrottleMaps) Close() error {
	return _CgthrottleClose(
		m.ThrottleAccum,
	)
}

// cgthrottleVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadCgthrottleObjects or ebpf.CollectionSpec.LoadAndAssign.
type cgthrottleVariables struct {
}

// cgthrottlePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadCgthrottleObjects or ebpf.CollectionSpec.LoadAndAssign.
type cgthrottlePrograms struct {
	HandleThrottleCfsRq *ebpf.Program `ebpf:"handle_throttle_cfs_rq"`
}

func (p *cgthrottlePrograms) Close() error {
	return _CgthrottleClose(
		p.HandleThrottleCfsRq,
	)
}

func _CgthrottleClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed cgthrottle_x86_bpfel.o
var _CgthrottleBytes []byte
