// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type connrateFlowKey struct {
	_     structs.HostLayout
	Pid   uint32
	Daddr uint32
}

type connrateFlowVal struct {
	_            structs.HostLayout
	ConnectCount uint64
	CloseCount   uint64
	FirstNs      uint64
}

// loadConnrate returns the embedded CollectionSpec for connrate.
func loadConnrate() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ConnrateBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load connrate: %w", err)
	}

	return spec, err
}

// loadConnrateObjects loads connrate and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*connrateObjects
//	*connratePrograms
//	*connrateMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadConnrateObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadConnrate()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// connrateSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type connrateSpecs struct {
	connrateProgramSpecs
	connrateMapSpecs
	connrateVariableSpecs
}

// connrateProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type connrateProgramSpecs struct {
	HandleConnrate *ebpf.ProgramSpec `ebpf:"handle_connrate"`
}

// connrateMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type connrateMapSpecs struct {
	DestCount *ebpf.MapSpec `ebpf:"dest_count"`
	FlowAccum *ebpf.MapSpec `ebpf:"flow_accum"`
}

// connrateVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type connrateVariableSpecs struct {
}

// connrateObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadConnrateObjects or ebpf.CollectionSpec.LoadAndAssign.
type connrateObjects struct {
	connratePrograms
	connrateMaps
	connrateVariables
}

func (o *connrateObjects) Close() error {
	return _ConnrateClose(
		&o.connratePrograms,
		&o.connrateMaps,
	)
}

// connrateMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadConnrateObjects or ebpf.CollectionSpec.LoadAndAssign.
type connrateMaps struct {
	DestCount *ebpf.Map `ebpf:"dest_count"`
	FlowAccum *ebpf.Map `ebpf:"flow_accum"`
}

func (m *connrateMaps) Close() error {
	return _ConnrateClose(
		m.DestCount,
		m.FlowAccum,
	)
}

// connrateVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadConnrateObjects or ebpf.CollectionSpec.LoadAndAssign.
type connrateVariables struct {
}

// connratePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadConnrateObjects or ebpf.CollectionSpec.LoadAndAssign.
type connratePrograms struct {
	HandleConnrate *ebpf.Program `ebpf:"handle_connrate"`
}

func (p *connratePrograms) Close() error {
	return _ConnrateClose(
		p.HandleConnrate,
	)
}

func _ConnrateClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed connrate_x86_bpfel.o
var _ConnrateBytes []byte
