// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadCpuprofile returns the embedded CollectionSpec for cpuprofile.
func loadCpuprofile() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_CpuprofileBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load cpuprofile: %w", err)
	}

	return spec, err
}

// loadCpuprofileObjects loads cpuprofile and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*cpuprofileObjects
//	*cpuprofilePrograms
//	*cpuprofileMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadCpuprofileObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadCpuprofile()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// cpuprofileSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type cpuprofileSpecs struct {
	cpuprofileProgramSpecs
	cpuprofileMapSpecs
	cpuprofileVariableSpecs
}

// cpuprofileProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type cpuprofileProgramSpecs struct {
	CpuProfile *ebpf.ProgramSpec `ebpf:"cpu_profile"`
}

// cpuprofileMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type cpuprofileMapSpecs struct {
	Counts      *ebpf.MapSpec `ebpf:"counts"`
	StackTraces *ebpf.MapSpec `ebpf:"stack_traces"`
}

// cpuprofileVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type cpuprofileVariableSpecs struct {
	TargetPid *ebpf.VariableSpec `ebpf:"target_pid"`
}

// cpuprofileObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadCpuprofileObjects or ebpf.CollectionSpec.LoadAndAssign.
type cpuprofileObjects struct {
	cpuprofilePrograms
	cpuprofileMaps
	cpuprofileVariables
}

func (o *cpuprofileObjects) Close() error {
	return _CpuprofileClose(
		&o.cpuprofilePrograms,
		&o.cpuprofileMaps,
	)
}

// cpuprofileMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadCpuprofileObjects or ebpf.CollectionSpec.LoadAndAssign.
type cpuprofileMaps struct {
	Counts      *ebpf.Map `ebpf:"counts"`
	StackTraces *ebpf.Map `ebpf:"stack_traces"`
}

func (m *cpuprofileMaps) Close() error {
	return _CpuprofileClose(
		m.Counts,
		m.StackTraces,
	)
}

// cpuprofileVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadCpuprofileObjects or ebpf.CollectionSpec.LoadAndAssign.
type cpuprofileVariables struct {
	TargetPid *ebpf.Variable `ebpf:"target_pid"`
}

// cpuprofilePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadCpuprofileObjects or ebpf.CollectionSpec.LoadAndAssign.
type cpuprofilePrograms struct {
	CpuProfile *ebpf.Program `ebpf:"cpu_profile"`
}

func (p *cpuprofilePrograms) Close() error {
	return _CpuprofileClose(
		p.CpuProfile,
	)
}

func _CpuprofileClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed cpuprofile_x86_bpfel.o
var _CpuprofileBytes []byte
