// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type directreclaimReclaimVal struct {
	_       structs.HostLayout
	StallNs uint64
	Count   uint32
	_       [4]byte
}

// loadDirectreclaim returns the embedded CollectionSpec for directreclaim.
func loadDirectreclaim() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_DirectreclaimBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load directreclaim: %w", err)
	}

	return spec, err
}

// loadDirectreclaimObjects loads directreclaim and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*directreclaimObjects
//	*directreclaimPrograms
//	*directreclaimMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadDirectreclaimObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadDirectreclaim()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// directreclaimSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type directreclaimSpecs struct {
	directreclaimProgramSpecs
	directreclaimMapSpecs
	directreclaimVariableSpecs
}

// directreclaimProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type directreclaimProgramSpecs struct {
	HandleReclaimBegin *ebpf.ProgramSpec `ebpf:"handle_reclaim_begin"`
	HandleReclaimEnd   *ebpf.ProgramSpec `ebpf:"handle_reclaim_end"`
}

// directreclaimMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type directreclaimMapSpecs struct {
	ReclaimAccum *ebpf.MapSpec `ebpf:"reclaim_accum"`
	ReclaimStart *ebpf.MapSpec `ebpf:"reclaim_start"`
}

// directreclaimVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type directreclaimVariableSpecs struct {
}

// directreclaimObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadDirectreclaimObjects or ebpf.CollectionSpec.LoadAndAssign.
type directreclaimObjects struct {
	directreclaimPrograms
	directreclaimMaps
	directreclaimVariables
}

func (o *directreclaimObjects) Close() error {
	return _DirectreclaimClose(
		&o.directreclaimPrograms,
		&o.directreclaimMaps,
	)
}

// directreclaimMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadDirectreclaimObjects or ebpf.CollectionSpec.LoadAndAssign.
type directreclaimMaps struct {
	ReclaimAccum *ebpf.Map `ebpf:"reclaim_accum"`
	ReclaimStart *ebpf.Map `ebpf:"reclaim_start"`
}

func (m *directreclaimMaps) Close() error {
	return _DirectreclaimClose(
		m.ReclaimAccum,
		m.ReclaimStart,
	)
}

// directreclaimVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadDirectreclaimObjects or ebpf.CollectionSpec.LoadAndAssign.
type directreclaimVariables struct {
}

// directreclaimPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadDirectreclaimObjects or ebpf.CollectionSpec.LoadAndAssign.
type directreclaimPrograms struct {
	HandleReclaimBegin *ebpf.Program `ebpf:"handle_reclaim_begin"`
	HandleReclaimEnd   *ebpf.Program `ebpf:"handle_reclaim_end"`
}

func (p *directreclaimPrograms) Close() error {
	return _DirectreclaimClose(
		p.HandleReclaimBegin,
		p.HandleReclaimEnd,
	)
}

func _DirectreclaimClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed directreclaim_x86_bpfel.o
var _DirectreclaimBytes []byte
