// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type dnsdeepDnsDeepVal struct {
	_               structs.HostLayout
	TotalQueries    uint64
	TxtQueries      uint64
	TotalQueryBytes uint64
	MaxNameLen      uint32
	_               [4]byte
}

// loadDnsdeep returns the embedded CollectionSpec for dnsdeep.
func loadDnsdeep() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_DnsdeepBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load dnsdeep: %w", err)
	}

	return spec, err
}

// loadDnsdeepObjects loads dnsdeep and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*dnsdeepObjects
//	*dnsdeepPrograms
//	*dnsdeepMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadDnsdeepObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadDnsdeep()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// dnsdeepSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type dnsdeepSpecs struct {
	dnsdeepProgramSpecs
	dnsdeepMapSpecs
	dnsdeepVariableSpecs
}

// dnsdeepProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type dnsdeepProgramSpecs struct {
	HandleDnsdeep *ebpf.ProgramSpec `ebpf:"handle_dnsdeep"`
}

// dnsdeepMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type dnsdeepMapSpecs struct {
	DnsDeep *ebpf.MapSpec `ebpf:"dns_deep"`
}

// dnsdeepVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type dnsdeepVariableSpecs struct {
}

// dnsdeepObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadDnsdeepObjects or ebpf.CollectionSpec.LoadAndAssign.
type dnsdeepObjects struct {
	dnsdeepPrograms
	dnsdeepMaps
	dnsdeepVariables
}

func (o *dnsdeepObjects) Close() error {
	return _DnsdeepClose(
		&o.dnsdeepPrograms,
		&o.dnsdeepMaps,
	)
}

// dnsdeepMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadDnsdeepObjects or ebpf.CollectionSpec.LoadAndAssign.
type dnsdeepMaps struct {
	DnsDeep *ebpf.Map `ebpf:"dns_deep"`
}

func (m *dnsdeepMaps) Close() error {
	return _DnsdeepClose(
		m.DnsDeep,
	)
}

// dnsdeepVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadDnsdeepObjects or ebpf.CollectionSpec.LoadAndAssign.
type dnsdeepVariables struct {
}

// dnsdeepPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadDnsdeepObjects or ebpf.CollectionSpec.LoadAndAssign.
type dnsdeepPrograms struct {
	HandleDnsdeep *ebpf.Program `ebpf:"handle_dnsdeep"`
}

func (p *dnsdeepPrograms) Close() error {
	return _DnsdeepClose(
		p.HandleDnsdeep,
	)
}

func _DnsdeepClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed dnsdeep_x86_bpfel.o
var _DnsdeepBytes []byte
