// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type dnsmonDnsVal struct {
	_               structs.HostLayout
	QueryCount      uint64
	TotalQueryBytes uint64
	TotalRespBytes  uint64
	MaxQueryLen     uint32
	_               [4]byte
}

// loadDnsmon returns the embedded CollectionSpec for dnsmon.
func loadDnsmon() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_DnsmonBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load dnsmon: %w", err)
	}

	return spec, err
}

// loadDnsmonObjects loads dnsmon and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*dnsmonObjects
//	*dnsmonPrograms
//	*dnsmonMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadDnsmonObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadDnsmon()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// dnsmonSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type dnsmonSpecs struct {
	dnsmonProgramSpecs
	dnsmonMapSpecs
	dnsmonVariableSpecs
}

// dnsmonProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type dnsmonProgramSpecs struct {
	HandleUdpRecvmsg *ebpf.ProgramSpec `ebpf:"handle_udp_recvmsg"`
	HandleUdpSendmsg *ebpf.ProgramSpec `ebpf:"handle_udp_sendmsg"`
}

// dnsmonMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type dnsmonMapSpecs struct {
	DnsAccum *ebpf.MapSpec `ebpf:"dns_accum"`
}

// dnsmonVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type dnsmonVariableSpecs struct {
}

// dnsmonObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadDnsmonObjects or ebpf.CollectionSpec.LoadAndAssign.
type dnsmonObjects struct {
	dnsmonPrograms
	dnsmonMaps
	dnsmonVariables
}

func (o *dnsmonObjects) Close() error {
	return _DnsmonClose(
		&o.dnsmonPrograms,
		&o.dnsmonMaps,
	)
}

// dnsmonMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadDnsmonObjects or ebpf.CollectionSpec.LoadAndAssign.
type dnsmonMaps struct {
	DnsAccum *ebpf.Map `ebpf:"dns_accum"`
}

func (m *dnsmonMaps) Close() error {
	return _DnsmonClose(
		m.DnsAccum,
	)
}

// dnsmonVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadDnsmonObjects or ebpf.CollectionSpec.LoadAndAssign.
type dnsmonVariables struct {
}

// dnsmonPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadDnsmonObjects or ebpf.CollectionSpec.LoadAndAssign.
type dnsmonPrograms struct {
	HandleUdpRecvmsg *ebpf.Program `ebpf:"handle_udp_recvmsg"`
	HandleUdpSendmsg *ebpf.Program `ebpf:"handle_udp_sendmsg"`
}

func (p *dnsmonPrograms) Close() error {
	return _DnsmonClose(
		p.HandleUdpRecvmsg,
		p.HandleUdpSendmsg,
	)
}

func _DnsmonClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed dnsmon_x86_bpfel.o
var _DnsmonBytes []byte
