// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type iolatencyIolatVal struct {
	_       structs.HostLayout
	TotalNs uint64
	MaxNs   uint64
	Count   uint32
	Slots   [16]uint32
	Dev     uint32
}

type iolatencyRqKey struct {
	_      structs.HostLayout
	Dev    uint32
	_      [4]byte
	Sector uint64
}

type iolatencyRqStart struct {
	_       structs.HostLayout
	Pid     uint32
	_       [4]byte
	StartNs uint64
}

// loadIolatency returns the embedded CollectionSpec for iolatency.
func loadIolatency() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_IolatencyBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load iolatency: %w", err)
	}

	return spec, err
}

// loadIolatencyObjects loads iolatency and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*iolatencyObjects
//	*iolatencyPrograms
//	*iolatencyMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadIolatencyObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadIolatency()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// iolatencySpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type iolatencySpecs struct {
	iolatencyProgramSpecs
	iolatencyMapSpecs
	iolatencyVariableSpecs
}

// iolatencyProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type iolatencyProgramSpecs struct {
	HandleBlockRqComplete *ebpf.ProgramSpec `ebpf:"handle_block_rq_complete"`
	HandleBlockRqIssue    *ebpf.ProgramSpec `ebpf:"handle_block_rq_issue"`
}

// iolatencyMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type iolatencyMapSpecs struct {
	Inflight  *ebpf.MapSpec `ebpf:"inflight"`
	IolatHist *ebpf.MapSpec `ebpf:"iolat_hist"`
}

// iolatencyVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type iolatencyVariableSpecs struct {
}

// iolatencyObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadIolatencyObjects or ebpf.CollectionSpec.LoadAndAssign.
type iolatencyObjects struct {
	iolatencyPrograms
	iolatencyMaps
	iolatencyVariables
}

func (o *iolatencyObjects) Close() error {
	return _IolatencyClose(
		&o.iolatencyPrograms,
		&o.iolatencyMaps,
	)
}

// iolatencyMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadIolatencyObjects or ebpf.CollectionSpec.LoadAndAssign.
type iolatencyMaps struct {
	Inflight  *ebpf.Map `ebpf:"inflight"`
	IolatHist *ebpf.Map `ebpf:"iolat_hist"`
}

func (m *iolatencyMaps) Close() error {
	return _IolatencyClose(
		m.Inflight,
		m.IolatHist,
	)
}

// iolatencyVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadIolatencyObjects or ebpf.CollectionSpec.LoadAndAssign.
type iolatencyVariables struct {
}

// iolatencyPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadIolatencyObjects or ebpf.CollectionSpec.LoadAndAssign.
type iolatencyPrograms struct {
	HandleBlockRqComplete *ebpf.Program `ebpf:"handle_block_rq_complete"`
	HandleBlockRqIssue    *ebpf.Program `ebpf:"handle_block_rq_issue"`
}

func (p *iolatencyPrograms) Close() error {
	return _IolatencyClose(
		p.HandleBlockRqComplete,
		p.HandleBlockRqIssue,
	)
}

func _IolatencyClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed iolatency_x86_bpfel.o
var _IolatencyBytes []byte
