// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type kfreeskbDropVal struct {
	_     structs.HostLayout
	Count uint64
}

// loadKfreeskb returns the embedded CollectionSpec for kfreeskb.
func loadKfreeskb() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_KfreeskbBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load kfreeskb: %w", err)
	}

	return spec, err
}

// loadKfreeskbObjects loads kfreeskb and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*kfreeskbObjects
//	*kfreeskbPrograms
//	*kfreeskbMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadKfreeskbObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadKfreeskb()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// kfreeskbSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type kfreeskbSpecs struct {
	kfreeskbProgramSpecs
	kfreeskbMapSpecs
	kfreeskbVariableSpecs
}

// kfreeskbProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type kfreeskbProgramSpecs struct {
	HandleKfreeSkb *ebpf.ProgramSpec `ebpf:"handle_kfree_skb"`
}

// kfreeskbMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type kfreeskbMapSpecs struct {
	DropAccum *ebpf.MapSpec `ebpf:"drop_accum"`
}

// kfreeskbVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type kfreeskbVariableSpecs struct {
}

// kfreeskbObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadKfreeskbObjects or ebpf.CollectionSpec.LoadAndAssign.
type kfreeskbObjects struct {
	kfreeskbPrograms
	kfreeskbMaps
	kfreeskbVariables
}

func (o *kfreeskbObjects) Close() error {
	return _KfreeskbClose(
		&o.kfreeskbPrograms,
		&o.kfreeskbMaps,
	)
}

// kfreeskbMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadKfreeskbObjects or ebpf.CollectionSpec.LoadAndAssign.
type kfreeskbMaps struct {
	DropAccum *ebpf.Map `ebpf:"drop_accum"`
}

func (m *kfreeskbMaps) Close() error {
	return _KfreeskbClose(
		m.DropAccum,
	)
}

// kfreeskbVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadKfreeskbObjects or ebpf.CollectionSpec.LoadAndAssign.
type kfreeskbVariables struct {
}

// kfreeskbPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadKfreeskbObjects or ebpf.CollectionSpec.LoadAndAssign.
type kfreeskbPrograms struct {
	HandleKfreeSkb *ebpf.Program `ebpf:"handle_kfree_skb"`
}

func (p *kfreeskbPrograms) Close() error {
	return _KfreeskbClose(
		p.HandleKfreeSkb,
	)
}

func _KfreeskbClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed kfreeskb_x86_bpfel.o
var _KfreeskbBytes []byte
