// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type lockwaitLockVal struct {
	_           structs.HostLayout
	TotalWaitNs uint64
	Count       uint32
	_           [4]byte
}

// loadLockwait returns the embedded CollectionSpec for lockwait.
func loadLockwait() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_LockwaitBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load lockwait: %w", err)
	}

	return spec, err
}

// loadLockwaitObjects loads lockwait and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*lockwaitObjects
//	*lockwaitPrograms
//	*lockwaitMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadLockwaitObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadLockwait()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// lockwaitSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lockwaitSpecs struct {
	lockwaitProgramSpecs
	lockwaitMapSpecs
	lockwaitVariableSpecs
}

// lockwaitProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lockwaitProgramSpecs struct {
	HandleFutexEnter *ebpf.ProgramSpec `ebpf:"handle_futex_enter"`
	HandleFutexExit  *ebpf.ProgramSpec `ebpf:"handle_futex_exit"`
}

// lockwaitMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lockwaitMapSpecs struct {
	FutexAccum *ebpf.MapSpec `ebpf:"futex_accum"`
	FutexStart *ebpf.MapSpec `ebpf:"futex_start"`
}

// lockwaitVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lockwaitVariableSpecs struct {
}

// lockwaitObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadLockwaitObjects or ebpf.CollectionSpec.LoadAndAssign.
type lockwaitObjects struct {
	lockwaitPrograms
	lockwaitMaps
	lockwaitVariables
}

func (o *lockwaitObjects) Close() error {
	return _LockwaitClose(
		&o.lockwaitPrograms,
		&o.lockwaitMaps,
	)
}

// lockwaitMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadLockwaitObjects or ebpf.CollectionSpec.LoadAndAssign.
type lockwaitMaps struct {
	FutexAccum *ebpf.Map `ebpf:"futex_accum"`
	FutexStart *ebpf.Map `ebpf:"futex_start"`
}

func (m *lockwaitMaps) Close() error {
	return _LockwaitClose(
		m.FutexAccum,
		m.FutexStart,
	)
}

// lockwaitVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadLockwaitObjects or ebpf.CollectionSpec.LoadAndAssign.
type lockwaitVariables struct {
}

// lockwaitPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadLockwaitObjects or ebpf.CollectionSpec.LoadAndAssign.
type lockwaitPrograms struct {
	HandleFutexEnter *ebpf.Program `ebpf:"handle_futex_enter"`
	HandleFutexExit  *ebpf.Program `ebpf:"handle_futex_exit"`
}

func (p *lockwaitPrograms) Close() error {
	return _LockwaitClose(
		p.HandleFutexEnter,
		p.HandleFutexExit,
	)
}

func _LockwaitClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed lockwait_x86_bpfel.o
var _LockwaitBytes []byte
