// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type modloadModVal struct {
	_     structs.HostLayout
	Count uint64
	Ts    uint64
	Name  [56]int8
}

// loadModload returns the embedded CollectionSpec for modload.
func loadModload() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ModloadBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load modload: %w", err)
	}

	return spec, err
}

// loadModloadObjects loads modload and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*modloadObjects
//	*modloadPrograms
//	*modloadMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadModloadObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadModload()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// modloadSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type modloadSpecs struct {
	modloadProgramSpecs
	modloadMapSpecs
	modloadVariableSpecs
}

// modloadProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type modloadProgramSpecs struct {
	HandleDoInitModule *ebpf.ProgramSpec `ebpf:"handle_do_init_module"`
}

// modloadMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type modloadMapSpecs struct {
	ModAccum *ebpf.MapSpec `ebpf:"mod_accum"`
}

// modloadVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type modloadVariableSpecs struct {
}

// modloadObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadModloadObjects or ebpf.CollectionSpec.LoadAndAssign.
type modloadObjects struct {
	modloadPrograms
	modloadMaps
	modloadVariables
}

func (o *modloadObjects) Close() error {
	return _ModloadClose(
		&o.modloadPrograms,
		&o.modloadMaps,
	)
}

// modloadMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadModloadObjects or ebpf.CollectionSpec.LoadAndAssign.
type modloadMaps struct {
	ModAccum *ebpf.Map `ebpf:"mod_accum"`
}

func (m *modloadMaps) Close() error {
	return _ModloadClose(
		m.ModAccum,
	)
}

// modloadVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadModloadObjects or ebpf.CollectionSpec.LoadAndAssign.
type modloadVariables struct {
}

// modloadPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadModloadObjects or ebpf.CollectionSpec.LoadAndAssign.
type modloadPrograms struct {
	HandleDoInitModule *ebpf.Program `ebpf:"handle_do_init_module"`
}

func (p *modloadPrograms) Close() error {
	return _ModloadClose(
		p.HandleDoInitModule,
	)
}

func _ModloadClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed modload_x86_bpfel.o
var _ModloadBytes []byte
