// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type netthroughputNetVal struct {
	_       structs.HostLayout
	TxBytes uint64
	RxBytes uint64
}

// loadNetthroughput returns the embedded CollectionSpec for netthroughput.
func loadNetthroughput() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_NetthroughputBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load netthroughput: %w", err)
	}

	return spec, err
}

// loadNetthroughputObjects loads netthroughput and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*netthroughputObjects
//	*netthroughputPrograms
//	*netthroughputMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadNetthroughputObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadNetthroughput()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// netthroughputSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type netthroughputSpecs struct {
	netthroughputProgramSpecs
	netthroughputMapSpecs
	netthroughputVariableSpecs
}

// netthroughputProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type netthroughputProgramSpecs struct {
	HandleTcpCleanupRbuf *ebpf.ProgramSpec `ebpf:"handle_tcp_cleanup_rbuf"`
	HandleTcpSendmsg     *ebpf.ProgramSpec `ebpf:"handle_tcp_sendmsg"`
}

// netthroughputMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type netthroughputMapSpecs struct {
	NetAccum *ebpf.MapSpec `ebpf:"net_accum"`
}

// netthroughputVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type netthroughputVariableSpecs struct {
}

// netthroughputObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadNetthroughputObjects or ebpf.CollectionSpec.LoadAndAssign.
type netthroughputObjects struct {
	netthroughputPrograms
	netthroughputMaps
	netthroughputVariables
}

func (o *netthroughputObjects) Close() error {
	return _NetthroughputClose(
		&o.netthroughputPrograms,
		&o.netthroughputMaps,
	)
}

// netthroughputMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadNetthroughputObjects or ebpf.CollectionSpec.LoadAndAssign.
type netthroughputMaps struct {
	NetAccum *ebpf.Map `ebpf:"net_accum"`
}

func (m *netthroughputMaps) Close() error {
	return _NetthroughputClose(
		m.NetAccum,
	)
}

// netthroughputVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadNetthroughputObjects or ebpf.CollectionSpec.LoadAndAssign.
type netthroughputVariables struct {
}

// netthroughputPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadNetthroughputObjects or ebpf.CollectionSpec.LoadAndAssign.
type netthroughputPrograms struct {
	HandleTcpCleanupRbuf *ebpf.Program `ebpf:"handle_tcp_cleanup_rbuf"`
	HandleTcpSendmsg     *ebpf.Program `ebpf:"handle_tcp_sendmsg"`
}

func (p *netthroughputPrograms) Close() error {
	return _NetthroughputClose(
		p.HandleTcpCleanupRbuf,
		p.HandleTcpSendmsg,
	)
}

func _NetthroughputClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed netthroughput_x86_bpfel.o
var _NetthroughputBytes []byte
