// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type offcpuOffcpuVal struct {
	_       structs.HostLayout
	TotalNs uint64
	Count   uint32
	_       [4]byte
}

// loadOffcpu returns the embedded CollectionSpec for offcpu.
func loadOffcpu() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_OffcpuBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load offcpu: %w", err)
	}

	return spec, err
}

// loadOffcpuObjects loads offcpu and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*offcpuObjects
//	*offcpuPrograms
//	*offcpuMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadOffcpuObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadOffcpu()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// offcpuSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type offcpuSpecs struct {
	offcpuProgramSpecs
	offcpuMapSpecs
	offcpuVariableSpecs
}

// offcpuProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type offcpuProgramSpecs struct {
	HandleSchedSwitch *ebpf.ProgramSpec `ebpf:"handle_sched_switch"`
}

// offcpuMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type offcpuMapSpecs struct {
	OffcpuAccum *ebpf.MapSpec `ebpf:"offcpu_accum"`
	OffcpuStart *ebpf.MapSpec `ebpf:"offcpu_start"`
}

// offcpuVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type offcpuVariableSpecs struct {
}

// offcpuObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadOffcpuObjects or ebpf.CollectionSpec.LoadAndAssign.
type offcpuObjects struct {
	offcpuPrograms
	offcpuMaps
	offcpuVariables
}

func (o *offcpuObjects) Close() error {
	return _OffcpuClose(
		&o.offcpuPrograms,
		&o.offcpuMaps,
	)
}

// offcpuMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadOffcpuObjects or ebpf.CollectionSpec.LoadAndAssign.
type offcpuMaps struct {
	OffcpuAccum *ebpf.Map `ebpf:"offcpu_accum"`
	OffcpuStart *ebpf.Map `ebpf:"offcpu_start"`
}

func (m *offcpuMaps) Close() error {
	return _OffcpuClose(
		m.OffcpuAccum,
		m.OffcpuStart,
	)
}

// offcpuVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadOffcpuObjects or ebpf.CollectionSpec.LoadAndAssign.
type offcpuVariables struct {
}

// offcpuPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadOffcpuObjects or ebpf.CollectionSpec.LoadAndAssign.
type offcpuPrograms struct {
	HandleSchedSwitch *ebpf.Program `ebpf:"handle_sched_switch"`
}

func (p *offcpuPrograms) Close() error {
	return _OffcpuClose(
		p.HandleSchedSwitch,
	)
}

func _OffcpuClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed offcpu_x86_bpfel.o
var _OffcpuBytes []byte
