// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type outboundEgressKey struct {
	_     structs.HostLayout
	Pid   uint32
	Daddr uint32
}

type outboundEgressVal struct {
	_           structs.HostLayout
	TotalBytes  uint64
	PacketCount uint64
	LastNs      uint64
}

// loadOutbound returns the embedded CollectionSpec for outbound.
func loadOutbound() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_OutboundBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load outbound: %w", err)
	}

	return spec, err
}

// loadOutboundObjects loads outbound and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*outboundObjects
//	*outboundPrograms
//	*outboundMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadOutboundObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadOutbound()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// outboundSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type outboundSpecs struct {
	outboundProgramSpecs
	outboundMapSpecs
	outboundVariableSpecs
}

// outboundProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type outboundProgramSpecs struct {
	HandleTcpSendmsgEgress *ebpf.ProgramSpec `ebpf:"handle_tcp_sendmsg_egress"`
}

// outboundMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type outboundMapSpecs struct {
	EgressAccum *ebpf.MapSpec `ebpf:"egress_accum"`
}

// outboundVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type outboundVariableSpecs struct {
}

// outboundObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadOutboundObjects or ebpf.CollectionSpec.LoadAndAssign.
type outboundObjects struct {
	outboundPrograms
	outboundMaps
	outboundVariables
}

func (o *outboundObjects) Close() error {
	return _OutboundClose(
		&o.outboundPrograms,
		&o.outboundMaps,
	)
}

// outboundMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadOutboundObjects or ebpf.CollectionSpec.LoadAndAssign.
type outboundMaps struct {
	EgressAccum *ebpf.Map `ebpf:"egress_accum"`
}

func (m *outboundMaps) Close() error {
	return _OutboundClose(
		m.EgressAccum,
	)
}

// outboundVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadOutboundObjects or ebpf.CollectionSpec.LoadAndAssign.
type outboundVariables struct {
}

// outboundPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadOutboundObjects or ebpf.CollectionSpec.LoadAndAssign.
type outboundPrograms struct {
	HandleTcpSendmsgEgress *ebpf.Program `ebpf:"handle_tcp_sendmsg_egress"`
}

func (p *outboundPrograms) Close() error {
	return _OutboundClose(
		p.HandleTcpSendmsgEgress,
	)
}

func _OutboundClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed outbound_x86_bpfel.o
var _OutboundBytes []byte
