// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type pgfaultPgfaultVal struct {
	_          structs.HostLayout
	TotalNs    uint64
	Count      uint32
	MajorCount uint32
}

// loadPgfault returns the embedded CollectionSpec for pgfault.
func loadPgfault() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_PgfaultBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load pgfault: %w", err)
	}

	return spec, err
}

// loadPgfaultObjects loads pgfault and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*pgfaultObjects
//	*pgfaultPrograms
//	*pgfaultMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadPgfaultObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadPgfault()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// pgfaultSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type pgfaultSpecs struct {
	pgfaultProgramSpecs
	pgfaultMapSpecs
	pgfaultVariableSpecs
}

// pgfaultProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type pgfaultProgramSpecs struct {
	HandleFaultEnter *ebpf.ProgramSpec `ebpf:"handle_fault_enter"`
	HandleFaultExit  *ebpf.ProgramSpec `ebpf:"handle_fault_exit"`
}

// pgfaultMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type pgfaultMapSpecs struct {
	PgfaultAccum *ebpf.MapSpec `ebpf:"pgfault_accum"`
	PgfaultStart *ebpf.MapSpec `ebpf:"pgfault_start"`
}

// pgfaultVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type pgfaultVariableSpecs struct {
}

// pgfaultObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadPgfaultObjects or ebpf.CollectionSpec.LoadAndAssign.
type pgfaultObjects struct {
	pgfaultPrograms
	pgfaultMaps
	pgfaultVariables
}

func (o *pgfaultObjects) Close() error {
	return _PgfaultClose(
		&o.pgfaultPrograms,
		&o.pgfaultMaps,
	)
}

// pgfaultMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadPgfaultObjects or ebpf.CollectionSpec.LoadAndAssign.
type pgfaultMaps struct {
	PgfaultAccum *ebpf.Map `ebpf:"pgfault_accum"`
	PgfaultStart *ebpf.Map `ebpf:"pgfault_start"`
}

func (m *pgfaultMaps) Close() error {
	return _PgfaultClose(
		m.PgfaultAccum,
		m.PgfaultStart,
	)
}

// pgfaultVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadPgfaultObjects or ebpf.CollectionSpec.LoadAndAssign.
type pgfaultVariables struct {
}

// pgfaultPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadPgfaultObjects or ebpf.CollectionSpec.LoadAndAssign.
type pgfaultPrograms struct {
	HandleFaultEnter *ebpf.Program `ebpf:"handle_fault_enter"`
	HandleFaultExit  *ebpf.Program `ebpf:"handle_fault_exit"`
}

func (p *pgfaultPrograms) Close() error {
	return _PgfaultClose(
		p.HandleFaultEnter,
		p.HandleFaultExit,
	)
}

func _PgfaultClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed pgfault_x86_bpfel.o
var _PgfaultBytes []byte
