// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type portscanScanVal struct {
	_          structs.HostLayout
	RstCount   uint64
	PortBitmap uint64
	FirstNs    uint64
}

// loadPortscan returns the embedded CollectionSpec for portscan.
func loadPortscan() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_PortscanBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load portscan: %w", err)
	}

	return spec, err
}

// loadPortscanObjects loads portscan and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*portscanObjects
//	*portscanPrograms
//	*portscanMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadPortscanObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadPortscan()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// portscanSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type portscanSpecs struct {
	portscanProgramSpecs
	portscanMapSpecs
	portscanVariableSpecs
}

// portscanProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type portscanProgramSpecs struct {
	HandleTcpV4SendReset *ebpf.ProgramSpec `ebpf:"handle_tcp_v4_send_reset"`
}

// portscanMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type portscanMapSpecs struct {
	ScanAccum *ebpf.MapSpec `ebpf:"scan_accum"`
}

// portscanVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type portscanVariableSpecs struct {
}

// portscanObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadPortscanObjects or ebpf.CollectionSpec.LoadAndAssign.
type portscanObjects struct {
	portscanPrograms
	portscanMaps
	portscanVariables
}

func (o *portscanObjects) Close() error {
	return _PortscanClose(
		&o.portscanPrograms,
		&o.portscanMaps,
	)
}

// portscanMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadPortscanObjects or ebpf.CollectionSpec.LoadAndAssign.
type portscanMaps struct {
	ScanAccum *ebpf.Map `ebpf:"scan_accum"`
}

func (m *portscanMaps) Close() error {
	return _PortscanClose(
		m.ScanAccum,
	)
}

// portscanVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadPortscanObjects or ebpf.CollectionSpec.LoadAndAssign.
type portscanVariables struct {
}

// portscanPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadPortscanObjects or ebpf.CollectionSpec.LoadAndAssign.
type portscanPrograms struct {
	HandleTcpV4SendReset *ebpf.Program `ebpf:"handle_tcp_v4_send_reset"`
}

func (p *portscanPrograms) Close() error {
	return _PortscanClose(
		p.HandleTcpV4SendReset,
	)
}

func _PortscanClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed portscan_x86_bpfel.o
var _PortscanBytes []byte
