// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type ptracedetectPtraceKey struct {
	_         structs.HostLayout
	TracerPid uint32
	TargetPid uint32
}

type ptracedetectPtraceVal struct {
	_          structs.HostLayout
	Count      uint64
	Ts         uint64
	Request    uint64
	TracerComm [16]int8
}

// loadPtracedetect returns the embedded CollectionSpec for ptracedetect.
func loadPtracedetect() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_PtracedetectBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load ptracedetect: %w", err)
	}

	return spec, err
}

// loadPtracedetectObjects loads ptracedetect and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*ptracedetectObjects
//	*ptracedetectPrograms
//	*ptracedetectMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadPtracedetectObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadPtracedetect()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// ptracedetectSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ptracedetectSpecs struct {
	ptracedetectProgramSpecs
	ptracedetectMapSpecs
	ptracedetectVariableSpecs
}

// ptracedetectProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ptracedetectProgramSpecs struct {
	HandleSysEnterPtrace *ebpf.ProgramSpec `ebpf:"handle_sys_enter_ptrace"`
}

// ptracedetectMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ptracedetectMapSpecs struct {
	PtraceAccum *ebpf.MapSpec `ebpf:"ptrace_accum"`
}

// ptracedetectVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ptracedetectVariableSpecs struct {
}

// ptracedetectObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadPtracedetectObjects or ebpf.CollectionSpec.LoadAndAssign.
type ptracedetectObjects struct {
	ptracedetectPrograms
	ptracedetectMaps
	ptracedetectVariables
}

func (o *ptracedetectObjects) Close() error {
	return _PtracedetectClose(
		&o.ptracedetectPrograms,
		&o.ptracedetectMaps,
	)
}

// ptracedetectMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadPtracedetectObjects or ebpf.CollectionSpec.LoadAndAssign.
type ptracedetectMaps struct {
	PtraceAccum *ebpf.Map `ebpf:"ptrace_accum"`
}

func (m *ptracedetectMaps) Close() error {
	return _PtracedetectClose(
		m.PtraceAccum,
	)
}

// ptracedetectVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadPtracedetectObjects or ebpf.CollectionSpec.LoadAndAssign.
type ptracedetectVariables struct {
}

// ptracedetectPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadPtracedetectObjects or ebpf.CollectionSpec.LoadAndAssign.
type ptracedetectPrograms struct {
	HandleSysEnterPtrace *ebpf.Program `ebpf:"handle_sys_enter_ptrace"`
}

func (p *ptracedetectPrograms) Close() error {
	return _PtracedetectClose(
		p.HandleSysEnterPtrace,
	)
}

func _PtracedetectClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed ptracedetect_x86_bpfel.o
var _PtracedetectBytes []byte
