// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type runqlatRqlatVal struct {
	_       structs.HostLayout
	TotalNs uint64
	Count   uint32
	MaxNs   uint32
}

// loadRunqlat returns the embedded CollectionSpec for runqlat.
func loadRunqlat() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_RunqlatBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load runqlat: %w", err)
	}

	return spec, err
}

// loadRunqlatObjects loads runqlat and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*runqlatObjects
//	*runqlatPrograms
//	*runqlatMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadRunqlatObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadRunqlat()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// runqlatSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type runqlatSpecs struct {
	runqlatProgramSpecs
	runqlatMapSpecs
	runqlatVariableSpecs
}

// runqlatProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type runqlatProgramSpecs struct {
	HandleSchedSwitchRqlat *ebpf.ProgramSpec `ebpf:"handle_sched_switch_rqlat"`
	HandleSchedWakeup      *ebpf.ProgramSpec `ebpf:"handle_sched_wakeup"`
}

// runqlatMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type runqlatMapSpecs struct {
	RqStart    *ebpf.MapSpec `ebpf:"rq_start"`
	RqlatAccum *ebpf.MapSpec `ebpf:"rqlat_accum"`
}

// runqlatVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type runqlatVariableSpecs struct {
}

// runqlatObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadRunqlatObjects or ebpf.CollectionSpec.LoadAndAssign.
type runqlatObjects struct {
	runqlatPrograms
	runqlatMaps
	runqlatVariables
}

func (o *runqlatObjects) Close() error {
	return _RunqlatClose(
		&o.runqlatPrograms,
		&o.runqlatMaps,
	)
}

// runqlatMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadRunqlatObjects or ebpf.CollectionSpec.LoadAndAssign.
type runqlatMaps struct {
	RqStart    *ebpf.Map `ebpf:"rq_start"`
	RqlatAccum *ebpf.Map `ebpf:"rqlat_accum"`
}

func (m *runqlatMaps) Close() error {
	return _RunqlatClose(
		m.RqStart,
		m.RqlatAccum,
	)
}

// runqlatVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadRunqlatObjects or ebpf.CollectionSpec.LoadAndAssign.
type runqlatVariables struct {
}

// runqlatPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadRunqlatObjects or ebpf.CollectionSpec.LoadAndAssign.
type runqlatPrograms struct {
	HandleSchedSwitchRqlat *ebpf.Program `ebpf:"handle_sched_switch_rqlat"`
	HandleSchedWakeup      *ebpf.Program `ebpf:"handle_sched_wakeup"`
}

func (p *runqlatPrograms) Close() error {
	return _RunqlatClose(
		p.HandleSchedSwitchRqlat,
		p.HandleSchedWakeup,
	)
}

func _RunqlatClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed runqlat_x86_bpfel.o
var _RunqlatBytes []byte
