// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type sockstateStateKey struct {
	_        structs.HostLayout
	Oldstate uint16
	Newstate uint16
}

type sockstateStateVal struct {
	_     structs.HostLayout
	Count uint64
}

// loadSockstate returns the embedded CollectionSpec for sockstate.
func loadSockstate() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_SockstateBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load sockstate: %w", err)
	}

	return spec, err
}

// loadSockstateObjects loads sockstate and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*sockstateObjects
//	*sockstatePrograms
//	*sockstateMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadSockstateObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadSockstate()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// sockstateSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type sockstateSpecs struct {
	sockstateProgramSpecs
	sockstateMapSpecs
	sockstateVariableSpecs
}

// sockstateProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type sockstateProgramSpecs struct {
	HandleSockSetState *ebpf.ProgramSpec `ebpf:"handle_sock_set_state"`
}

// sockstateMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type sockstateMapSpecs struct {
	StateAccum *ebpf.MapSpec `ebpf:"state_accum"`
}

// sockstateVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type sockstateVariableSpecs struct {
}

// sockstateObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadSockstateObjects or ebpf.CollectionSpec.LoadAndAssign.
type sockstateObjects struct {
	sockstatePrograms
	sockstateMaps
	sockstateVariables
}

func (o *sockstateObjects) Close() error {
	return _SockstateClose(
		&o.sockstatePrograms,
		&o.sockstateMaps,
	)
}

// sockstateMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadSockstateObjects or ebpf.CollectionSpec.LoadAndAssign.
type sockstateMaps struct {
	StateAccum *ebpf.Map `ebpf:"state_accum"`
}

func (m *sockstateMaps) Close() error {
	return _SockstateClose(
		m.StateAccum,
	)
}

// sockstateVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadSockstateObjects or ebpf.CollectionSpec.LoadAndAssign.
type sockstateVariables struct {
}

// sockstatePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadSockstateObjects or ebpf.CollectionSpec.LoadAndAssign.
type sockstatePrograms struct {
	HandleSockSetState *ebpf.Program `ebpf:"handle_sock_set_state"`
}

func (p *sockstatePrograms) Close() error {
	return _SockstateClose(
		p.HandleSockSetState,
	)
}

func _SockstateClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed sockstate_x86_bpfel.o
var _SockstateBytes []byte
