// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type sockioRecvStart struct {
	_     structs.HostLayout
	Ts    uint64
	Daddr uint32
	Dport uint16
	Pad   uint16
}

type sockioSockioKey struct {
	_     structs.HostLayout
	Pid   uint32
	Daddr uint32
	Dport uint16
	Pad   uint16
}

type sockioSockioVal struct {
	_          structs.HostLayout
	TxBytes    uint64
	RxBytes    uint64
	RecvWaitNs uint64
	RecvCount  uint32
	MaxRecvNs  uint32
}

// loadSockio returns the embedded CollectionSpec for sockio.
func loadSockio() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_SockioBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load sockio: %w", err)
	}

	return spec, err
}

// loadSockioObjects loads sockio and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*sockioObjects
//	*sockioPrograms
//	*sockioMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadSockioObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadSockio()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// sockioSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type sockioSpecs struct {
	sockioProgramSpecs
	sockioMapSpecs
	sockioVariableSpecs
}

// sockioProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type sockioProgramSpecs struct {
	HandleTcpCleanupRbuf  *ebpf.ProgramSpec `ebpf:"handle_tcp_cleanup_rbuf"`
	HandleTcpRecvmsgEnter *ebpf.ProgramSpec `ebpf:"handle_tcp_recvmsg_enter"`
	HandleTcpRecvmsgExit  *ebpf.ProgramSpec `ebpf:"handle_tcp_recvmsg_exit"`
	HandleTcpSendmsg      *ebpf.ProgramSpec `ebpf:"handle_tcp_sendmsg"`
}

// sockioMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type sockioMapSpecs struct {
	RecvInflight *ebpf.MapSpec `ebpf:"recv_inflight"`
	SockioAccum  *ebpf.MapSpec `ebpf:"sockio_accum"`
}

// sockioVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type sockioVariableSpecs struct {
}

// sockioObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadSockioObjects or ebpf.CollectionSpec.LoadAndAssign.
type sockioObjects struct {
	sockioPrograms
	sockioMaps
	sockioVariables
}

func (o *sockioObjects) Close() error {
	return _SockioClose(
		&o.sockioPrograms,
		&o.sockioMaps,
	)
}

// sockioMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadSockioObjects or ebpf.CollectionSpec.LoadAndAssign.
type sockioMaps struct {
	RecvInflight *ebpf.Map `ebpf:"recv_inflight"`
	SockioAccum  *ebpf.Map `ebpf:"sockio_accum"`
}

func (m *sockioMaps) Close() error {
	return _SockioClose(
		m.RecvInflight,
		m.SockioAccum,
	)
}

// sockioVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadSockioObjects or ebpf.CollectionSpec.LoadAndAssign.
type sockioVariables struct {
}

// sockioPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadSockioObjects or ebpf.CollectionSpec.LoadAndAssign.
type sockioPrograms struct {
	HandleTcpCleanupRbuf  *ebpf.Program `ebpf:"handle_tcp_cleanup_rbuf"`
	HandleTcpRecvmsgEnter *ebpf.Program `ebpf:"handle_tcp_recvmsg_enter"`
	HandleTcpRecvmsgExit  *ebpf.Program `ebpf:"handle_tcp_recvmsg_exit"`
	HandleTcpSendmsg      *ebpf.Program `ebpf:"handle_tcp_sendmsg"`
}

func (p *sockioPrograms) Close() error {
	return _SockioClose(
		p.HandleTcpCleanupRbuf,
		p.HandleTcpRecvmsgEnter,
		p.HandleTcpRecvmsgExit,
		p.HandleTcpSendmsg,
	)
}

func _SockioClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed sockio_x86_bpfel.o
var _SockioBytes []byte
