// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type swapevictSwapVal struct {
	_          structs.HostLayout
	ReadPages  uint64
	WritePages uint64
}

// loadSwapevict returns the embedded CollectionSpec for swapevict.
func loadSwapevict() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_SwapevictBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load swapevict: %w", err)
	}

	return spec, err
}

// loadSwapevictObjects loads swapevict and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*swapevictObjects
//	*swapevictPrograms
//	*swapevictMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadSwapevictObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadSwapevict()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// swapevictSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type swapevictSpecs struct {
	swapevictProgramSpecs
	swapevictMapSpecs
	swapevictVariableSpecs
}

// swapevictProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type swapevictProgramSpecs struct {
	HandleSwapReadpage  *ebpf.ProgramSpec `ebpf:"handle_swap_readpage"`
	HandleSwapWritepage *ebpf.ProgramSpec `ebpf:"handle_swap_writepage"`
}

// swapevictMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type swapevictMapSpecs struct {
	SwapAccum *ebpf.MapSpec `ebpf:"swap_accum"`
}

// swapevictVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type swapevictVariableSpecs struct {
}

// swapevictObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadSwapevictObjects or ebpf.CollectionSpec.LoadAndAssign.
type swapevictObjects struct {
	swapevictPrograms
	swapevictMaps
	swapevictVariables
}

func (o *swapevictObjects) Close() error {
	return _SwapevictClose(
		&o.swapevictPrograms,
		&o.swapevictMaps,
	)
}

// swapevictMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadSwapevictObjects or ebpf.CollectionSpec.LoadAndAssign.
type swapevictMaps struct {
	SwapAccum *ebpf.Map `ebpf:"swap_accum"`
}

func (m *swapevictMaps) Close() error {
	return _SwapevictClose(
		m.SwapAccum,
	)
}

// swapevictVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadSwapevictObjects or ebpf.CollectionSpec.LoadAndAssign.
type swapevictVariables struct {
}

// swapevictPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadSwapevictObjects or ebpf.CollectionSpec.LoadAndAssign.
type swapevictPrograms struct {
	HandleSwapReadpage  *ebpf.Program `ebpf:"handle_swap_readpage"`
	HandleSwapWritepage *ebpf.Program `ebpf:"handle_swap_writepage"`
}

func (p *swapevictPrograms) Close() error {
	return _SwapevictClose(
		p.HandleSwapReadpage,
		p.HandleSwapWritepage,
	)
}

func _SwapevictClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed swapevict_x86_bpfel.o
var _SwapevictBytes []byte
