// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type synfloodSynVal struct {
	_             structs.HostLayout
	SynCount      uint64
	SynackRetrans uint64
	FirstNs       uint64
}

// loadSynflood returns the embedded CollectionSpec for synflood.
func loadSynflood() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_SynfloodBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load synflood: %w", err)
	}

	return spec, err
}

// loadSynfloodObjects loads synflood and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*synfloodObjects
//	*synfloodPrograms
//	*synfloodMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadSynfloodObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadSynflood()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// synfloodSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type synfloodSpecs struct {
	synfloodProgramSpecs
	synfloodMapSpecs
	synfloodVariableSpecs
}

// synfloodProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type synfloodProgramSpecs struct {
	HandleTcpConnRequest      *ebpf.ProgramSpec `ebpf:"handle_tcp_conn_request"`
	HandleTcpRetransmitSynack *ebpf.ProgramSpec `ebpf:"handle_tcp_retransmit_synack"`
}

// synfloodMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type synfloodMapSpecs struct {
	SynAccum *ebpf.MapSpec `ebpf:"syn_accum"`
}

// synfloodVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type synfloodVariableSpecs struct {
}

// synfloodObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadSynfloodObjects or ebpf.CollectionSpec.LoadAndAssign.
type synfloodObjects struct {
	synfloodPrograms
	synfloodMaps
	synfloodVariables
}

func (o *synfloodObjects) Close() error {
	return _SynfloodClose(
		&o.synfloodPrograms,
		&o.synfloodMaps,
	)
}

// synfloodMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadSynfloodObjects or ebpf.CollectionSpec.LoadAndAssign.
type synfloodMaps struct {
	SynAccum *ebpf.Map `ebpf:"syn_accum"`
}

func (m *synfloodMaps) Close() error {
	return _SynfloodClose(
		m.SynAccum,
	)
}

// synfloodVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadSynfloodObjects or ebpf.CollectionSpec.LoadAndAssign.
type synfloodVariables struct {
}

// synfloodPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadSynfloodObjects or ebpf.CollectionSpec.LoadAndAssign.
type synfloodPrograms struct {
	HandleTcpConnRequest      *ebpf.Program `ebpf:"handle_tcp_conn_request"`
	HandleTcpRetransmitSynack *ebpf.Program `ebpf:"handle_tcp_retransmit_synack"`
}

func (p *synfloodPrograms) Close() error {
	return _SynfloodClose(
		p.HandleTcpConnRequest,
		p.HandleTcpRetransmitSynack,
	)
}

func _SynfloodClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed synflood_x86_bpfel.o
var _SynfloodBytes []byte
