// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type syscalldissectScKey struct {
	_         structs.HostLayout
	Pid       uint32
	SyscallNr uint32
}

type syscalldissectScVal struct {
	_       structs.HostLayout
	TotalNs uint64
	Count   uint32
	MaxNs   uint32
}

// loadSyscalldissect returns the embedded CollectionSpec for syscalldissect.
func loadSyscalldissect() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_SyscalldissectBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load syscalldissect: %w", err)
	}

	return spec, err
}

// loadSyscalldissectObjects loads syscalldissect and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*syscalldissectObjects
//	*syscalldissectPrograms
//	*syscalldissectMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadSyscalldissectObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadSyscalldissect()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// syscalldissectSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type syscalldissectSpecs struct {
	syscalldissectProgramSpecs
	syscalldissectMapSpecs
	syscalldissectVariableSpecs
}

// syscalldissectProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type syscalldissectProgramSpecs struct {
	HandleSysEnter *ebpf.ProgramSpec `ebpf:"handle_sys_enter"`
	HandleSysExit  *ebpf.ProgramSpec `ebpf:"handle_sys_exit"`
}

// syscalldissectMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type syscalldissectMapSpecs struct {
	ScAccum *ebpf.MapSpec `ebpf:"sc_accum"`
	ScStart *ebpf.MapSpec `ebpf:"sc_start"`
}

// syscalldissectVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type syscalldissectVariableSpecs struct {
}

// syscalldissectObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadSyscalldissectObjects or ebpf.CollectionSpec.LoadAndAssign.
type syscalldissectObjects struct {
	syscalldissectPrograms
	syscalldissectMaps
	syscalldissectVariables
}

func (o *syscalldissectObjects) Close() error {
	return _SyscalldissectClose(
		&o.syscalldissectPrograms,
		&o.syscalldissectMaps,
	)
}

// syscalldissectMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadSyscalldissectObjects or ebpf.CollectionSpec.LoadAndAssign.
type syscalldissectMaps struct {
	ScAccum *ebpf.Map `ebpf:"sc_accum"`
	ScStart *ebpf.Map `ebpf:"sc_start"`
}

func (m *syscalldissectMaps) Close() error {
	return _SyscalldissectClose(
		m.ScAccum,
		m.ScStart,
	)
}

// syscalldissectVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadSyscalldissectObjects or ebpf.CollectionSpec.LoadAndAssign.
type syscalldissectVariables struct {
}

// syscalldissectPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadSyscalldissectObjects or ebpf.CollectionSpec.LoadAndAssign.
type syscalldissectPrograms struct {
	HandleSysEnter *ebpf.Program `ebpf:"handle_sys_enter"`
	HandleSysExit  *ebpf.Program `ebpf:"handle_sys_exit"`
}

func (p *syscalldissectPrograms) Close() error {
	return _SyscalldissectClose(
		p.HandleSysEnter,
		p.HandleSysExit,
	)
}

func _SyscalldissectClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed syscalldissect_x86_bpfel.o
var _SyscalldissectBytes []byte
