// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type tcpconnlatConnStart struct {
	_   structs.HostLayout
	Ts  uint64
	Pid uint32
	_   [4]byte
}

type tcpconnlatConnlatVal struct {
	_       structs.HostLayout
	TotalNs uint64
	Count   uint32
	MaxNs   uint32
	LastPid uint32
	Daddr   uint32
}

// loadTcpconnlat returns the embedded CollectionSpec for tcpconnlat.
func loadTcpconnlat() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TcpconnlatBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load tcpconnlat: %w", err)
	}

	return spec, err
}

// loadTcpconnlatObjects loads tcpconnlat and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*tcpconnlatObjects
//	*tcpconnlatPrograms
//	*tcpconnlatMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTcpconnlatObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadTcpconnlat()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// tcpconnlatSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpconnlatSpecs struct {
	tcpconnlatProgramSpecs
	tcpconnlatMapSpecs
	tcpconnlatVariableSpecs
}

// tcpconnlatProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpconnlatProgramSpecs struct {
	HandleSetState     *ebpf.ProgramSpec `ebpf:"handle_set_state"`
	HandleTcpV4Connect *ebpf.ProgramSpec `ebpf:"handle_tcp_v4_connect"`
}

// tcpconnlatMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpconnlatMapSpecs struct {
	ConnInflight *ebpf.MapSpec `ebpf:"conn_inflight"`
	ConnlatAccum *ebpf.MapSpec `ebpf:"connlat_accum"`
}

// tcpconnlatVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpconnlatVariableSpecs struct {
}

// tcpconnlatObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTcpconnlatObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpconnlatObjects struct {
	tcpconnlatPrograms
	tcpconnlatMaps
	tcpconnlatVariables
}

func (o *tcpconnlatObjects) Close() error {
	return _TcpconnlatClose(
		&o.tcpconnlatPrograms,
		&o.tcpconnlatMaps,
	)
}

// tcpconnlatMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTcpconnlatObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpconnlatMaps struct {
	ConnInflight *ebpf.Map `ebpf:"conn_inflight"`
	ConnlatAccum *ebpf.Map `ebpf:"connlat_accum"`
}

func (m *tcpconnlatMaps) Close() error {
	return _TcpconnlatClose(
		m.ConnInflight,
		m.ConnlatAccum,
	)
}

// tcpconnlatVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTcpconnlatObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpconnlatVariables struct {
}

// tcpconnlatPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTcpconnlatObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpconnlatPrograms struct {
	HandleSetState     *ebpf.Program `ebpf:"handle_set_state"`
	HandleTcpV4Connect *ebpf.Program `ebpf:"handle_tcp_v4_connect"`
}

func (p *tcpconnlatPrograms) Close() error {
	return _TcpconnlatClose(
		p.HandleSetState,
		p.HandleTcpV4Connect,
	)
}

func _TcpconnlatClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tcpconnlat_x86_bpfel.o
var _TcpconnlatBytes []byte
