// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type tcpflagsFlagsKey struct {
	_     structs.HostLayout
	Saddr uint32
	Flags uint8
	Pad   [3]uint8
}

type tcpflagsFlagsVal struct {
	_     structs.HostLayout
	Count uint64
}

// loadTcpflags returns the embedded CollectionSpec for tcpflags.
func loadTcpflags() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TcpflagsBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load tcpflags: %w", err)
	}

	return spec, err
}

// loadTcpflagsObjects loads tcpflags and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*tcpflagsObjects
//	*tcpflagsPrograms
//	*tcpflagsMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTcpflagsObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadTcpflags()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// tcpflagsSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpflagsSpecs struct {
	tcpflagsProgramSpecs
	tcpflagsMapSpecs
	tcpflagsVariableSpecs
}

// tcpflagsProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpflagsProgramSpecs struct {
	HandleTcpflags *ebpf.ProgramSpec `ebpf:"handle_tcpflags"`
}

// tcpflagsMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpflagsMapSpecs struct {
	FlagsAccum *ebpf.MapSpec `ebpf:"flags_accum"`
}

// tcpflagsVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpflagsVariableSpecs struct {
}

// tcpflagsObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTcpflagsObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpflagsObjects struct {
	tcpflagsPrograms
	tcpflagsMaps
	tcpflagsVariables
}

func (o *tcpflagsObjects) Close() error {
	return _TcpflagsClose(
		&o.tcpflagsPrograms,
		&o.tcpflagsMaps,
	)
}

// tcpflagsMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTcpflagsObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpflagsMaps struct {
	FlagsAccum *ebpf.Map `ebpf:"flags_accum"`
}

func (m *tcpflagsMaps) Close() error {
	return _TcpflagsClose(
		m.FlagsAccum,
	)
}

// tcpflagsVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTcpflagsObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpflagsVariables struct {
}

// tcpflagsPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTcpflagsObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpflagsPrograms struct {
	HandleTcpflags *ebpf.Program `ebpf:"handle_tcpflags"`
}

func (p *tcpflagsPrograms) Close() error {
	return _TcpflagsClose(
		p.HandleTcpflags,
	)
}

func _TcpflagsClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tcpflags_x86_bpfel.o
var _TcpflagsBytes []byte
