// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type tcpresetResetVal struct {
	_         structs.HostLayout
	Count     uint64
	LastDaddr uint32
	LastDport uint16
	_         [2]byte
}

// loadTcpreset returns the embedded CollectionSpec for tcpreset.
func loadTcpreset() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TcpresetBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load tcpreset: %w", err)
	}

	return spec, err
}

// loadTcpresetObjects loads tcpreset and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*tcpresetObjects
//	*tcpresetPrograms
//	*tcpresetMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTcpresetObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadTcpreset()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// tcpresetSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpresetSpecs struct {
	tcpresetProgramSpecs
	tcpresetMapSpecs
	tcpresetVariableSpecs
}

// tcpresetProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpresetProgramSpecs struct {
	HandleTcpSendReset *ebpf.ProgramSpec `ebpf:"handle_tcp_send_reset"`
}

// tcpresetMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpresetMapSpecs struct {
	ResetAccum *ebpf.MapSpec `ebpf:"reset_accum"`
}

// tcpresetVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpresetVariableSpecs struct {
}

// tcpresetObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTcpresetObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpresetObjects struct {
	tcpresetPrograms
	tcpresetMaps
	tcpresetVariables
}

func (o *tcpresetObjects) Close() error {
	return _TcpresetClose(
		&o.tcpresetPrograms,
		&o.tcpresetMaps,
	)
}

// tcpresetMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTcpresetObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpresetMaps struct {
	ResetAccum *ebpf.Map `ebpf:"reset_accum"`
}

func (m *tcpresetMaps) Close() error {
	return _TcpresetClose(
		m.ResetAccum,
	)
}

// tcpresetVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTcpresetObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpresetVariables struct {
}

// tcpresetPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTcpresetObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpresetPrograms struct {
	HandleTcpSendReset *ebpf.Program `ebpf:"handle_tcp_send_reset"`
}

func (p *tcpresetPrograms) Close() error {
	return _TcpresetClose(
		p.HandleTcpSendReset,
	)
}

func _TcpresetClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tcpreset_x86_bpfel.o
var _TcpresetBytes []byte
