// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type tcprttRttKey struct {
	_     structs.HostLayout
	Daddr uint32
	Dport uint16
	Pad   uint16
}

type tcprttRttVal struct {
	_       structs.HostLayout
	SumUs   uint64
	Count   uint32
	MinUs   uint32
	MaxUs   uint32
	LastPid uint32
}

// loadTcprtt returns the embedded CollectionSpec for tcprtt.
func loadTcprtt() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TcprttBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load tcprtt: %w", err)
	}

	return spec, err
}

// loadTcprttObjects loads tcprtt and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*tcprttObjects
//	*tcprttPrograms
//	*tcprttMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTcprttObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadTcprtt()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// tcprttSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcprttSpecs struct {
	tcprttProgramSpecs
	tcprttMapSpecs
	tcprttVariableSpecs
}

// tcprttProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcprttProgramSpecs struct {
	HandleTcpRcvEstablished *ebpf.ProgramSpec `ebpf:"handle_tcp_rcv_established"`
}

// tcprttMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcprttMapSpecs struct {
	RttAccum *ebpf.MapSpec `ebpf:"rtt_accum"`
}

// tcprttVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcprttVariableSpecs struct {
}

// tcprttObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTcprttObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcprttObjects struct {
	tcprttPrograms
	tcprttMaps
	tcprttVariables
}

func (o *tcprttObjects) Close() error {
	return _TcprttClose(
		&o.tcprttPrograms,
		&o.tcprttMaps,
	)
}

// tcprttMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTcprttObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcprttMaps struct {
	RttAccum *ebpf.Map `ebpf:"rtt_accum"`
}

func (m *tcprttMaps) Close() error {
	return _TcprttClose(
		m.RttAccum,
	)
}

// tcprttVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTcprttObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcprttVariables struct {
}

// tcprttPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTcprttObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcprttPrograms struct {
	HandleTcpRcvEstablished *ebpf.Program `ebpf:"handle_tcp_rcv_established"`
}

func (p *tcprttPrograms) Close() error {
	return _TcprttClose(
		p.HandleTcpRcvEstablished,
	)
}

func _TcprttClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tcprtt_x86_bpfel.o
var _TcprttBytes []byte
