// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type tcpretransRetransVal struct {
	_         structs.HostLayout
	Count     uint32
	LastSport uint16
	LastDport uint16
	LastDaddr uint32
}

// loadTcpretrans returns the embedded CollectionSpec for tcpretrans.
func loadTcpretrans() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TcpretransBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load tcpretrans: %w", err)
	}

	return spec, err
}

// loadTcpretransObjects loads tcpretrans and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*tcpretransObjects
//	*tcpretransPrograms
//	*tcpretransMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTcpretransObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadTcpretrans()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// tcpretransSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpretransSpecs struct {
	tcpretransProgramSpecs
	tcpretransMapSpecs
	tcpretransVariableSpecs
}

// tcpretransProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpretransProgramSpecs struct {
	HandleTcpRetransmit *ebpf.ProgramSpec `ebpf:"handle_tcp_retransmit"`
}

// tcpretransMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpretransMapSpecs struct {
	RetransAccum *ebpf.MapSpec `ebpf:"retrans_accum"`
}

// tcpretransVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpretransVariableSpecs struct {
}

// tcpretransObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTcpretransObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpretransObjects struct {
	tcpretransPrograms
	tcpretransMaps
	tcpretransVariables
}

func (o *tcpretransObjects) Close() error {
	return _TcpretransClose(
		&o.tcpretransPrograms,
		&o.tcpretransMaps,
	)
}

// tcpretransMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTcpretransObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpretransMaps struct {
	RetransAccum *ebpf.Map `ebpf:"retrans_accum"`
}

func (m *tcpretransMaps) Close() error {
	return _TcpretransClose(
		m.RetransAccum,
	)
}

// tcpretransVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTcpretransObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpretransVariables struct {
}

// tcpretransPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTcpretransObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpretransPrograms struct {
	HandleTcpRetransmit *ebpf.Program `ebpf:"handle_tcp_retransmit"`
}

func (p *tcpretransPrograms) Close() error {
	return _TcpretransClose(
		p.HandleTcpRetransmit,
	)
}

func _TcpretransClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tcpretrans_x86_bpfel.o
var _TcpretransBytes []byte
