// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type tlsfingerJa3Val struct {
	_           structs.HostLayout
	Count       uint64
	SampleSaddr uint32
	SampleDaddr uint32
	TlsVersion  uint16
	CipherCount uint16
	_           [4]byte
}

// loadTlsfinger returns the embedded CollectionSpec for tlsfinger.
func loadTlsfinger() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TlsfingerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load tlsfinger: %w", err)
	}

	return spec, err
}

// loadTlsfingerObjects loads tlsfinger and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*tlsfingerObjects
//	*tlsfingerPrograms
//	*tlsfingerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTlsfingerObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadTlsfinger()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// tlsfingerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tlsfingerSpecs struct {
	tlsfingerProgramSpecs
	tlsfingerMapSpecs
	tlsfingerVariableSpecs
}

// tlsfingerProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tlsfingerProgramSpecs struct {
	HandleTlsfinger *ebpf.ProgramSpec `ebpf:"handle_tlsfinger"`
}

// tlsfingerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tlsfingerMapSpecs struct {
	Ja3Accum *ebpf.MapSpec `ebpf:"ja3_accum"`
}

// tlsfingerVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tlsfingerVariableSpecs struct {
}

// tlsfingerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTlsfingerObjects or ebpf.CollectionSpec.LoadAndAssign.
type tlsfingerObjects struct {
	tlsfingerPrograms
	tlsfingerMaps
	tlsfingerVariables
}

func (o *tlsfingerObjects) Close() error {
	return _TlsfingerClose(
		&o.tlsfingerPrograms,
		&o.tlsfingerMaps,
	)
}

// tlsfingerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTlsfingerObjects or ebpf.CollectionSpec.LoadAndAssign.
type tlsfingerMaps struct {
	Ja3Accum *ebpf.Map `ebpf:"ja3_accum"`
}

func (m *tlsfingerMaps) Close() error {
	return _TlsfingerClose(
		m.Ja3Accum,
	)
}

// tlsfingerVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTlsfingerObjects or ebpf.CollectionSpec.LoadAndAssign.
type tlsfingerVariables struct {
}

// tlsfingerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTlsfingerObjects or ebpf.CollectionSpec.LoadAndAssign.
type tlsfingerPrograms struct {
	HandleTlsfinger *ebpf.Program `ebpf:"handle_tlsfinger"`
}

func (p *tlsfingerPrograms) Close() error {
	return _TlsfingerClose(
		p.HandleTlsfinger,
	)
}

func _TlsfingerClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tlsfinger_x86_bpfel.o
var _TlsfingerBytes []byte
