// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type wbstallWbVal struct {
	_          structs.HostLayout
	Count      uint64
	TotalPages uint64
}

// loadWbstall returns the embedded CollectionSpec for wbstall.
func loadWbstall() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_WbstallBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load wbstall: %w", err)
	}

	return spec, err
}

// loadWbstallObjects loads wbstall and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*wbstallObjects
//	*wbstallPrograms
//	*wbstallMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadWbstallObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadWbstall()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// wbstallSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type wbstallSpecs struct {
	wbstallProgramSpecs
	wbstallMapSpecs
	wbstallVariableSpecs
}

// wbstallProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type wbstallProgramSpecs struct {
	HandleWritebackWait *ebpf.ProgramSpec `ebpf:"handle_writeback_wait"`
}

// wbstallMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type wbstallMapSpecs struct {
	WbAccum *ebpf.MapSpec `ebpf:"wb_accum"`
}

// wbstallVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type wbstallVariableSpecs struct {
}

// wbstallObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadWbstallObjects or ebpf.CollectionSpec.LoadAndAssign.
type wbstallObjects struct {
	wbstallPrograms
	wbstallMaps
	wbstallVariables
}

func (o *wbstallObjects) Close() error {
	return _WbstallClose(
		&o.wbstallPrograms,
		&o.wbstallMaps,
	)
}

// wbstallMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadWbstallObjects or ebpf.CollectionSpec.LoadAndAssign.
type wbstallMaps struct {
	WbAccum *ebpf.Map `ebpf:"wb_accum"`
}

func (m *wbstallMaps) Close() error {
	return _WbstallClose(
		m.WbAccum,
	)
}

// wbstallVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadWbstallObjects or ebpf.CollectionSpec.LoadAndAssign.
type wbstallVariables struct {
}

// wbstallPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadWbstallObjects or ebpf.CollectionSpec.LoadAndAssign.
type wbstallPrograms struct {
	HandleWritebackWait *ebpf.Program `ebpf:"handle_writeback_wait"`
}

func (p *wbstallPrograms) Close() error {
	return _WbstallClose(
		p.HandleWritebackWait,
	)
}

func _WbstallClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed wbstall_x86_bpfel.o
var _WbstallBytes []byte
